# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Drinkthedrink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    # Pods for Drinkthedrink
  pod 'UberRides'
	pod 'GoogleMaps'
        pod 'GooglePlaces'
        pod 'SDWebImage'
        pod 'SVProgressHUD'
	pod 'IQKeyboardManagerSwift'
	pod 'AFNetworking', '~> 3.0'
	pod 'Firebase/Analytics'
        pod 'Firebase/Messaging'



  target 'DrinkthedrinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrinkthedrinkUITests' do
    # Pods for testing
  end

end
